### ISSUE TITLE
روی سرور پول نمیشود

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam-Document#12]
======CMD======
cd ***
git fetch --all
git pull
cp index.html fa/
cp index.html en/

======END======
err: From https://github.com/SalamLang/Salam-Document
err:  + 737da6c...900ca20 main       -> origin/main  (forced update)
err: hint: You have divergent branches and need to specify how to reconcile them.
err: hint: You can do so by running one of the following commands sometime before
err: hint: your next pull:
err: hint: 
err: hint:   git config pull.rebase false  # merge
err: hint:   git config pull.rebase true   # rebase
err: hint:   git config pull.ff only       # fast-forward only
err: hint: 
err: hint: You can replace "git config" with "git config --global" to set a default
err: hint: preference for all repositories. You can also pass --rebase, --no-rebase,
err: hint: or --ff-only on the command line to override the configured default per
err: hint: invocation.
err: fatal: Need to specify how to reconcile divergent branches.
==============================================
✅ Successfully executed commands to all host.

**Comment by BaseMax** [comment]
I fixed the problem on the server.

Now CICD should works.

```
root@maxbasecode:/var/www/html/docs.salamlang.ir# git reset --hard HEAD
HEAD is now at 737da6c Update README.md
root@maxbasecode:/var/www/html/docs.salamlang.ir# git fetch origin
root@maxbasecode:/var/www/html/docs.salamlang.ir# git reset --hard origin/main
HEAD is now at 900ca20 feat(command)
root@maxbasecode:/var/www/html/docs.salamlang.ir# git pull
Already up to date.
root@maxbasecode:/var/www/html/docs.salamlang.ir# git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
root@maxbasecode:/var/www/html/docs.salamlang.ir# git pull
Already up to date.
```
